[package]
name = "mtl-text"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.0"

metal = "0.23.1"
cocoa = "0.24.0"
core-graphics-types = "0.1.1"
objc = "0.2.7"
swash = "0.1.4"
