[package]
name = "mtl-text"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.26.0"
smallvec = "1.6.1"
swash = "0.1.4"

metal = "0.22"
cocoa = "0.24.0"
objc = "0.2.5"
